name: t2341
on:
  workflow_dispatch:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Hello World
  Hell222o:
    runs-on: ubuntu-latest
    needs: Hello
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Hello World
  Hello234:
    runs-on: ubuntu-latest
    needs: Hell222o
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Hello World
  Dependency_Scanning_NPM_Dependency_Audit:
    name: Dependency Scanning-NPM Dependency Audit
    runs-on: ubuntu-latest
    needs: Hello234
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: echo hhhhhhhh
  Dependency_Scanning_OWASP_Dependency_Check:
    name: Dependency Scanning-OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: Hello234
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: echo ok
  Hell222o345:
    runs-on: ubuntu-latest
    needs:
    - Dependency_Scanning_NPM_Dependency_Audit
    - Dependency_Scanning_OWASP_Dependency_Check
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Hello World
